steps:
  - name: 'gcr.io/cloudbuild/docker'
    args: ['build', '-t', 'us-docker.pkg.dev/helical-button-425403-t3/cloudrun/my-python-app:latest', '.']
  - name: 'gcr.io/cloudbuild/docker'
    args: ['push', 'us-docker.pkg.dev/helical-button-425403-t3/cloudrun/my-python-app:latest']
  - name: 'gcr.io/cloudbuild/cloudrun'
    args: ['deploy', 'my-python-app', '--image', 'us-docker.pkg.dev/helical-button-425403-t3/cloudrun/my-python-app:latest', '--region', 'us-central1', '--platform', 'managed']
