steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-python-service', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-python-service']
  - name: 'gcr.io/google.com/cloudsdktool/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-python-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/my-python-service'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
  substitutions:
    #GCP Specific configuration. Please DON'T change anything
    _PROJECT: helical-button-425403-t3
    _ZONE: us-central1-a
